### ISSUE TITLE
Suggestion: check token

### ISSUE THREAD

**Issue by drazisil** [TheRealJoeLinux/circlecli#3]
Should check that token is a 40 digit hex string, and possibly check it is valid with /me prior to storing.

This can prevent errors when trying to use it, especially if circlecli is used in a batch script

**Comment by particledecay** [comment]
@drazisil This should be working in the latest release.

**Comment by particledecay** [comment]
@drazisil Also just added validating `circle.yml` files, per the CircleCI docs (including fields that aren't allowed, correct YAML, required values, correct value types, etc).

```
circlecli check circle.yml
```
