### ISSUE TITLE
Possible Bug: recent builds won't return json

### ISSUE THREAD

**Issue by drazisil** [TheRealJoeLinux/circlecli#5]
.builds(True) still returns an Ordict

I would expect it to return JSON, but is that not possible?

**Comment by particledecay** [comment]
The args for `.builds()` are `username`, `project`, `build_num`, and `verbose`. So if you only submitted `True`, that would go into `username` instead of `verbose`. You'd have to specify:

`.builds(verbose=True)` <-- that definitely returns JSON.

**Comment by drazisil** [comment]
Ah, thank you. I forgot to come back and close this after confirming
